kotlin.code.style=official

## Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Minecraft Properties
minecraftVersion=1.20.6
minecraftVersionRange=[1.20.6,1.21)
forgeVersion=50.1.0
forgeVersionRange=[0,)
loaderVersionRange=[0,)
mappingChannel=official
mappingVersion=1.20.6

## Mod Properties
modId=minecraftforgekotliner
modName=Minecraft Forge Kotliner
modLicense=All Rights Reserved
modVersion=1.0.0
modGroupId=io.toroponz.minecraftforgekotliner
modAuthors=toro_ponz
modDescription=A mod of minecraft forge by kotlin.
